import { DomNode, el, GameNode, ImageNode, SpineNode } from "skydapp-browser";
import CloneCraft from "../CloneCraft";
import Ready from "./battle/Ready";

export default class Battle extends GameNode {

    public content: DomNode;

    constructor() {
        super(0, 0);
        let spine: SpineNode;
        this.dom = el(".battle",
            this.content = el(".content",
                el("header",
                    el("a",
                        el("img", { src: "/images/battle/back.png", alt: "back" }),
                        {
                            click: () => CloneCraft.goWorld(),
                        },
                    ),
                ),
                el("main",
                    el(".player-container",
                        el(".profile",
                            el("img", { src: "" }),
                        ),
                        el(".clone-container",
                            el(".clone-slot",
                                el(".profile",
                                    el("img", { src: "" }),
                                ),
                                el(".hpbar-container",
                                    el(".bar"),
                                ),
                            ),
                        ),
                        el(".skill-container",
                            el("")
                        ),
                    ),
                    el(".battle-container",
                        el("header",
                            el(".name", "0x53..B5S1"),
                            el("img", { src: "/images/battle/VS.png", alt: "alt" }),
                            el(".name", "CLONESNEVER"),
                        ),
                        el("main",
                            el(".top-container",
                                el(".slot-container",
                                    el(".clone-slot",
                                        el(".profile",
                                            el("img", { src: "" }),
                                        ),
                                        el(".hpbar-container",
                                            el(".bar"),
                                        ),
                                    ),
                                    el(".large-clone-slot",
                                        el(".profile",
                                            el("img", { src: "" }),
                                        ),
                                        el(".hpbar-container",
                                            el(".bar"),
                                        ),
                                    ),
                                ),
                                el(".image-container",
                                    el("img", { src: "", alt: "battle" }),
                                ),
                                el(".slot-container",
                                    el(".clone-slot",
                                        el(".big-profile",
                                            el("img", { src: "" }),
                                        ),
                                        el(".hpbar-container",
                                            el(".bar"),
                                        ),
                                    ),
                                    el(".clone-slot",
                                        el(".profile",
                                            el("img", { src: "" }),
                                        ),
                                        el(".hpbar-container",
                                            el(".bar"),
                                        ),
                                    ),
                                ),
                            ),
                            el(".clone-container",
                                el(".sub-container",
                                    el(".slot-container",
                                        el(".clone-slot",
                                            el(".profile",
                                                el("img", { src: "" }),
                                            ),
                                            el(".hpbar-container",
                                                el(".bar"),
                                            ),
                                        ),
                                        el(".clone-slot",
                                            el(".profile",
                                                el("img", { src: "" }),
                                            ),
                                            el(".hpbar-container",
                                                el(".bar"),
                                            ),
                                        ),
                                        el(".clone-slot",
                                            el(".profile",
                                                el("img", { src: "" }),
                                            ),
                                            el(".hpbar-container",
                                                el(".bar"),
                                            ),
                                        ),
                                        el(".clone-slot",
                                            el(".profile",
                                                el("img", { src: "" }),
                                            ),
                                            el(".hpbar-container",
                                                el(".bar"),
                                            ),
                                        ),
                                    ),
                                    el(".property-container",
                                        el(".image-container",
                                            el("img", { src: "/images/ui/aqua.png", alt: "aqua" }),
                                        ),
                                        el(".image-container",
                                            el("img", { src: "/images/ui/aqua.png", alt: "aqua" }),
                                        ),
                                        el(".image-container",
                                            el("img", { src: "/images/ui/aqua.png", alt: "aqua" }),
                                        ),
                                    ),
                                ),
                                el(".log-container",
                                    el("p", "Player One Take Damage!"),
                                ),
                                el(".sub-container",
                                    el(".slot-container",
                                        el(".clone-slot",
                                            el(".profile",
                                                el("img", { src: "" }),
                                            ),
                                            el(".hpbar-container",
                                                el(".bar"),
                                            ),
                                        ),
                                        el(".clone-slot",
                                            el(".profile",
                                                el("img", { src: "" }),
                                            ),
                                            el(".hpbar-container",
                                                el(".bar"),
                                            ),
                                        ),
                                        el(".clone-slot",
                                            el(".profile",
                                                el("img", { src: "" }),
                                            ),
                                            el(".hpbar-container",
                                                el(".bar"),
                                            ),
                                        ),
                                        el(".clone-slot",
                                            el(".profile",
                                                el("img", { src: "" }),
                                            ),
                                            el(".hpbar-container",
                                                el(".bar"),
                                            ),
                                        ),
                                    ),
                                    el(".property-container",
                                        el(".image-container",
                                            el("img", { src: "/images/ui/aqua.png", alt: "aqua" }),
                                        ),
                                        el(".image-container",
                                            el("img", { src: "/images/ui/aqua.png", alt: "aqua" }),
                                        ),
                                        el(".image-container",
                                            el("img", { src: "/images/ui/aqua.png", alt: "aqua" }),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    el(".enemy-container",
                        el(".profile",
                            el("img", { src: "" }),
                        ),
                    ),
                ),
            ),
        );

        this.append(new ImageNode(0, 0, "/images/battle/battlefield.png"));

        const ready = new Ready().appendTo(this);
        ready.on("next", () => {
            console.log("next");
        });
    }
}
