"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const skydapp_browser_1 = require("skydapp-browser");
class UnitEquipPopup extends skydapp_browser_1.FixedNode {
    constructor() {
        super(0, 0);
        this.dom = (0, skydapp_browser_1.el)(".popup-background", this.content = (0, skydapp_browser_1.el)(".unit-equip-popup", (0, skydapp_browser_1.el)(".top", (0, skydapp_browser_1.el)(""), (0, skydapp_browser_1.el)("h6", "Clone Information"), (0, skydapp_browser_1.el)("a.close-button", (0, skydapp_browser_1.el)("img", { src: "/images/ui/close-button.png" }), { click: () => this.delete() })), (0, skydapp_browser_1.el)(".content", (0, skydapp_browser_1.el)(".character-container", (0, skydapp_browser_1.el)("img.character", { src: "/images/character/character1.jpeg" }), (0, skydapp_browser_1.el)(".slot-container", (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" }), (0, skydapp_browser_1.el)("img.slot", { src: "/images/character/unit-slot.png", alt: "unit-slot" })), (0, skydapp_browser_1.el)(".tab-container", (0, skydapp_browser_1.el)("a", "STATUS"), (0, skydapp_browser_1.el)("a", "EQUIP"))), (0, skydapp_browser_1.el)(".equip-container", (0, skydapp_browser_1.el)(".tab-container", (0, skydapp_browser_1.el)("a", "BACKGROUND"), (0, skydapp_browser_1.el)("a", "SITUATION"), (0, skydapp_browser_1.el)("a", "WEAPON"), (0, skydapp_browser_1.el)("a", "BODY"), (0, skydapp_browser_1.el)("a", "TATTO"), (0, skydapp_browser_1.el)("a", "MOUTH"), (0, skydapp_browser_1.el)("a", "EYES"), (0, skydapp_browser_1.el)("a", "CLOTHES"), (0, skydapp_browser_1.el)("a", "HAT"), (0, skydapp_browser_1.el)("a", "ACCESSORY"), (0, skydapp_browser_1.el)("a", "MASK"), (0, skydapp_browser_1.el)("a", "EFFECT")), (0, skydapp_browser_1.el)("section", (0, skydapp_browser_1.el)(".item", (0, skydapp_browser_1.el)("img", { src: "/images/profile-image-sample.png", alt: "items" }), (0, skydapp_browser_1.el)("a", "INFO")), (0, skydapp_browser_1.el)(".item", (0, skydapp_browser_1.el)("img", { src: "/images/profile-image-sample.png", alt: "items" }), (0, skydapp_browser_1.el)("a", "INFO")))))));
    }
}
exports.default = UnitEquipPopup;
//# sourceMappingURL=UnitEquipPopup.js.map